### ISSUE TITLE
Transition from rxtx to rx adminStatus doesn't work

### ISSUE THREAD

**Issue by misterdorm** [razorsedge/puppet-openlldp#11]
If a port's current adminStatus is "rxtx" and the requested state is "rx", the transition does not happen because of the grep pattern at https://github.com/razorsedge/puppet-openlldp/blob/master/manifests/config/lldp.pp#L74

A grep pattern of "adminStatus=rx" matches against "adminStatus=rxtx", so the set-lldp command is not executed in this case.

**Comment by razorsedge** [comment]
Fixed in #12 .
