### ISSUE TITLE
OpenLLDP with foreman.

### ISSUE THREAD

**Issue by alvinstarr** [razorsedge/puppet-openlldp#5]
I get the feeling that openlldp will not work with foreman to configure the interfaces.
I am a foreman and puppet newbie so I am likely missing something.
If you could point me at an example of lldp within foreman  that would be great.

**Comment by jb11211** [comment]
I wrote a patchset for theforeman which combines the openlldp config from this project with changes to the latest forman discovery image to make this work. see:
https://github.com/theforeman/foreman-discovery-image/pull/29

**Comment by razorsedge** [comment]
@alvinstarr I have no working knowledge of the Foreman.
@jb11211 Nice!
